# action.yml
name: "cppcheck action"
description: "read cppcheck result and post review comment to pull request"
inputs:
  github_token:
    description: "action github token"
    required: true
  repository:
    description: "owner and repository name"
    required: true
  pull_request_id:
    description: "pull request id"
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/setup-go@v2
      with:
        go-version: ^1.17.1
    - name: install depend
      shell: bash
      run: |
        sudo apt-get install -y cppcheck
        go env -w GO111MODULE=on
        go install github.com/myml/action-cppcheck/cmd/action-cppcheck@latest
    - name: generate
      shell: bash
      run: cppcheck --enable=all --output-file=report.xml  --xml .
    - name: command
      shell: bash
      run: action-cppcheck -repo=${{ inputs.repository }} -pr=${{ inputs.pull_request_id }} -f=report.xml
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
