# action.yml
name: "cppcheck action"
description: "read cppcheck result and post review comment to pull request"
inputs:
  github_token: # id of input
    description: "action github token"
    required: true
  repository:
    description: "owner and repository name"
    required: true
  pull_request_id:
    description: "pull request id"
    required: true
  cppcheck_file:
    description: "cppcheck_file"
    required: true

runs:
  using: "docker"
  image: "Dockerfile"
  env:
    GITHUB_TOKEN: ${{ inputs.github_token }}
  args:
    - "-repo"
    - ${{ inputs.repository }}
    - "-pr"
    - ${{ inputs.pull_request_id }}
    - "-f"
    - ${{ inputs.cppcheck_file }}
