# action.yml
name: "cppcheck action"
description: "read cppcheck result and post review comment to pull request"
inputs:
  github_token: # id of input
    description: "action github token"
    required: true
  repository:
    description: "owner and repository name"
    required: true
  pull_request_id:
    description: "pull request id"
    required: true
  cppcheck_file:
    description: "cppcheck_file"
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/setup-go@v2
    - name: install depend
      shell: bash
      run: |
        sudo apt-get install -y cppcheck
        go install github.com/myml/action-cppcheck/cmd/action-cppcheck@latest
    - name: generate
      shell: bash
      run: cppcheck --enable=all --output-file=report.xml  --xml .
    - name: command
      shell: bash
      run: action-cppcheck --help
